# Grafana setup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ui-grafana

resources:
- resources/data-ui-grafana.persistentvolumeclaim.yaml
- resources/ui-grafana.ingressroute.traefik.yaml
- resources/ui-grafana.service.yaml
- resources/ui-grafana.statefulset.yaml

replicas:
- name: ui-grafana
  count: 1

images:
- name: grafana/grafana
  newTag: 8.5.2
