apiVersion: v1
kind: PersistentVolume

metadata:
  name: data-prometheus
spec:
  capacity:
    storage: 9.8G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/monitoring-ssd/prometheus-data/k3smnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3sagent02
