apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: data-server-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  volumeName: data-prometheus
  resources:
    requests:
      storage: 9.8G