apiVersion: v1
kind: Service

metadata:
  name: agent-prometheus-node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9100'
spec:
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100
